### ISSUE TITLE
garbage in gameboy border

### ISSUE THREAD

**Issue by AaronBPaden** [libretro/slang-shaders#70] opened 2018-01-24 03:04 UTC
I'm getting garbage in the border of the slang dmg shaders. The glsl shaders seem to work fine.

Vulkan:
![screenshot from 2018-01-23 20-12-40](https://user-images.githubusercontent.com/1188012/35311250-30525f90-007b-11e8-99e9-9b5f5d420bbd.png)
GL:
![screenshot from 2018-01-23 20-24-17](https://user-images.githubusercontent.com/1188012/35312419-f0f910c2-0080-11e8-9fe2-53b42337b52d.png)

**Comment by hizzlekizzle** [comment] 2018-01-24 04:00
What kind of GPU do you have? Can you try replacing the border image with something transparent so we can see what the garbage actually looks like?

**Comment by BPaden** [comment] 2018-01-24 07:44
Sure I have an old GCN card. I forget the exact model but it's like a radeon 240x or something like that.

![screenshot from 2018-01-24 01-33-46](https://user-images.githubusercontent.com/1188012/35319864-4d66fb1e-00a7-11e8-8662-b141d94921e1.png)

**Comment by hizzlekizzle** [comment] 2018-01-25 02:33
Hmm, that's a lot of garbage... If you take the console-border out of it and just use the regular gameboy shader at a non-integer scale (that is, so there's some dead space around the image), is there garbage there, too?

**Comment by BPaden** [comment] 2018-01-25 12:05
Yep, looks that way

![screenshot from 2018-01-25 04-02-00](https://user-images.githubusercontent.com/1188012/35387493-98ec85ce-0195-11e8-8075-dcad3fa708d3.png)

**Comment by hizzlekizzle** [comment] 2018-01-25 20:24
Ok, my guess is that when it samples outside of the image, it returns random garbage. I think the workaround would be to specifically return 0.0 instead, but I'm not sure where we would add it and I can't really test it to find out (no machines with RADV driver).

**Comment by BPaden** [comment] 2018-01-26 17:43
Well I was messing around with the shader, only to realize I only have the vaguest idea about how shaders work. 😅

I can more or less read code though, and I'm not seeing anything, for example in the fragment shader of pass 4, to prevent from reading the forground (texel?) when out of bounds of the texture.

If you can put a test at the end of pass4 to determine if you're out of bounds of the foreground texture, you can just return bg_color I think. But, having no idea what I'm doing, I couldn't figure out how to test that theory out.

**Comment by hizzlekizzle** [comment] 2018-01-26 22:01
Try adding this (all one line) just above the return line (FragColor = out_color;) in gb-pass0.slang:
out_color = ((vTexCoord.x < 0.9999) && (vTexCoord.x > 0.0001) && (vTexCoord.y < 0.9999) && (vTexCoord.y > 0.0001)) ? out_color : vec4(0.0);

**Comment by BPaden** [comment] 2018-02-07 06:14
This doesn't quite work. With those numbers, I don't see any effect. You could create a border by playing around with the numbers, but it doesn't extend to the end of the screen as you might expect.

'out_color = ((vTexCoord.x < 0.98) && (vTexCoord.x > 0.02) && (vTexCoord.y < 0.98) && (vTexCoord.y > 0.02)) ? out_color : vec4(0.0);`

results in this:
![screenshot from 2018-02-07 00-07-14](https://user-images.githubusercontent.com/1188012/35901186-03fbb77c-0b9b-11e8-8209-7550d6e131c1.png)

It appears to be shaving pixels out of the game rather than the area outside of it.

I also tried adapting this to my hunch by putting it in pass4, but I realized there's no shadow so it just looks wrong. Putting the above line at the end of pass4 and replacing `vec4(0.0)` with `background` results in this:

![screenshot from 2018-02-06 22-40-48](https://user-images.githubusercontent.com/1188012/35898980-60679a28-0b8f-11e8-9257-489937101c52.png)

**Comment by Awakened0** [comment] 2018-03-23 03:10
I noticed this with the gameboy-pocket shader. I'm on a GTX 970.

GLSL:
![glsl](https://user-images.githubusercontent.com/4565863/37809353-51a5496e-2e25-11e8-8a94-890278343632.png)
Slang:
![slang](https://user-images.githubusercontent.com/4565863/37809361-5da76a58-2e25-11e8-8b83-7f8362e51d8c.png)
 
I can turn on integer scale to hide it, but it seems the alignment is slightly off so I get a light line around the left side and top.

**Comment by Awakened0** [comment] 2018-03-23 03:12
Integer comparison:

GLSL:
![integer-glsl](https://user-images.githubusercontent.com/4565863/37809531-3cf72e00-2e26-11e8-8a0a-3db36ab70f19.png)

Slang:
![integer-slang](https://user-images.githubusercontent.com/4565863/37809537-42905cf6-2e26-11e8-91d8-a7ad951df554.png)

Opening both images in tabs and switching between them shows the alignment difference (looks like one pixel?).

**Comment by BlueNinja0** [comment] 2018-05-08 23:41
I have this exact same problem and I'm on an NVIDIA GeForce GTX 680 on Windows 10.
This does not happen on the GLSL shaders on OpenGL. Only on the SLANG shaders on Vulkan.
![gb shader border bug 1](https://user-images.githubusercontent.com/11202422/39788300-baaec356-5321-11e8-9122-c9aca95dc9d1.PNG)
![gb shader border bug 2](https://user-images.githubusercontent.com/11202422/39788301-bac9e8d4-5321-11e8-8522-5a8d0312024b.PNG)

**Comment by BlueNinja0** [comment] 2018-05-08 23:57
I have uploaded a video that shows in greater detail the weird behavior. Notice that simply changing the Integer Scale setting on and off makes random garbage appear. Similarly, cycling between different shaders also makes the garbage change.
Notice that even the event of the OST message disappearing makes the garbage change or disappear too.
[https://youtu.be/TbgcFI65C3U](url)

This does not happen on the GLSL version of the shader. What could be causing this?

**Comment by hizzlekizzle** [comment] 2018-05-09 03:35
@BlueNinja0 I couldn't tell from your video: does disabling integer scaling resolve it?

**Comment by BlueNinja0** [comment] 2018-05-09 10:03
@hizzlekizzle No, it doesn't fix it. It just changes the garbage displayed to a different set of garbage. Sometimes it looks like it cleans up but it doesn't. Very strange behavior.

Here are 2 more screenshots. One when running the content for the 1st time, with the shader already set up beforehand, and another when cycling shaders.

1st run:
![1st run](https://user-images.githubusercontent.com/11202422/39808748-b48bcc20-5377-11e8-8656-fa46c9697352.PNG)

The area around the screen should be clear, not dark.



After cycling through shaders:
![shader change](https://user-images.githubusercontent.com/11202422/39808787-ca893e22-5377-11e8-85c4-76dea6904e72.PNG)

On the last picture I was changing between dmg-2x.slangp and dmg-3x.slangp. Notice how on the 3X shader (that I pasted above) there's some remainder pixels from the 2X shader where the words "Game Boy" were located. This does not always happens. It seems random.

**Comment by BlueNinja0** [comment] 2018-08-02 09:24
This issue seems to be fixed on my end.
I don't know what fixed it. It was either one of the recent commits or an Nvidia driver update. Or perhaps a Windows update?
The border garbage is gone and the shaders seem to be working as expected. Can anyone else confirm this?

**Comment by BPaden** [comment] 2018-08-02 22:09
Still an issue with radv.

**Comment by Awakened0** [comment] 2018-08-04 21:49
It's weird. I just tried tried dmg-5x.slangp and didn't see any garbage in the border, but then I loaded gb-pocket-5x.slangp and got this:

![kirby s dream land usa europe -180804-173946](https://user-images.githubusercontent.com/4565863/43680700-f30462d4-980d-11e8-9765-7d41b7306c99.png)

Using the latest NVidia drivers with the latest RetroArch nightly with a fresh pull of shaders from this repository. The gameboy-pocket non-console border shader I like to use still has the one pixel line along the top and left that isn't there in GLSL too.

**Comment by BlueNinja0** [comment] 2018-08-04 22:50
@Awakened0 I updated my Nvidia drivers to the latest version (398.82) and tried to replicate our steps, but I couldn't reproduce the garbage showing up. I still runs fine here. No garbage.
I'm not using RetroArch nightly though. I'm using 1.7.3 stable.

**Comment by Awakened0** [comment] 2019-01-18 03:05
I've updated to Windows 10 build 1809 (October), Nvidia driver 417.71 and an RA nightly from yesterday (d70a49ea6f2c8a2071f6dff6a5b08dfe4a03d212) and still get this issue with my GTX 970. The pocket console border shader looks about the same as the last screenshot I posted.

**Comment by Awakened0** [comment] 2019-01-23 03:31
I had some time to use DDU in safe mode to clean the drivers out and reinstall, but this still happens:

![donkey kong world rev a sgb enhanced -190122-222859](https://user-images.githubusercontent.com/4565863/51581263-5534e100-1e95-11e9-9e6a-76f3082b7167.png)

**Comment by nfp0** [comment] 2019-02-14 22:28
I had this problem fixed before by something when using a GeForce GTX 680 but now that I've bought a new RTX 2060 the problem is back!
This is after a clean re-installation of the drivers. I can replicate the exact same set of garbage pixels every time. It's the exact same I had before.

Since I can replicate the exact pixels every time, is there a way for me to help?

**Comment by Awakened0** [comment] 2019-03-18 01:15
Just thought I'd mention, the new glcore video driver shows the same issue. Same with d3d11 and d3d12.

**Comment by nfp0** [comment] 2019-03-18 10:17
@Awakened0 I don't have this issue on d3d12 on my RTX 2060
Are you on the latest NVidia drivers?

**Comment by Awakened0** [comment] 2019-03-18 19:28
Yeah, 419.35. I'm usually loading my default shader choice choice for GB, "handheld\gameboy-pocket.slangp" and looking for the thin white lines on the top and left that shouldn't be there. It's most noticeable on the Donkey Kong title screen since it uses mostly dark shades. When I loaded "handheld\console-border\dmg-6x.slangp" in d3d12, I actually didn't see any garbage. I've noticed the garbage isn't always consistently there though, while the white lines in the non console border version are always there.

**Comment by nfp0** [comment] 2019-03-19 22:56
@Awakened0 That might be an unrelated problem, but I don't see those thin white lines on gameboy-pocket.slangp on d3d12.

![RetroArch Screenshot 2019 03 19 - 22 48 10 91](https://user-images.githubusercontent.com/11202422/54647095-361f8d80-4a99-11e9-9bba-c1042255ef41.png)

Yes, the garbage is not consistent, it depends on what shader was set previously. For example, you can trigger the garbage by cycling through the handheld border shaders with the n and m hotkeys, as you can observe on this video https://youtu.be/TbgcFI65C3U at about 0:20 and as I described in my post here https://github.com/libretro/slang-shaders/issues/70#issuecomment-387689382
Mind you that's happening on Vulkan, and NOT on d3d12 for me.

**Comment by Awakened0** [comment] 2019-03-20 01:28
You should be able to see it if you run at 1:1 or core aspect, which gives you a black border. In a 6x window with core aspect this is how it compares between glsl on the gl driver and slang on vulkan: http://screenshotcomparison.com/comparison/132457

So it seems to be shifted down and to the right a pixel compared to glsl. Maybe it is a separate issue. I just thought since it's sort of an "graphic artifact outside the gameplay" problem it was related to the garbage.

I can confirm that cycling through the GB slang shaders in "handheld\console-border" does produce garbage in vulkan, but does not in d3d12.

**Comment by nfp0** [comment] 2019-05-08 18:39
I suggest editing the issue name, since this is not exclusive to radv.

**Closed** 2023-10-12 03:26 UTC
